---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-web
  name: nginx-web-service
spec:
  ports:
  - targetPort: 32000
    protocol: TCP
    port: 80
  selector:
    app: nginx-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-web
  name: nginx-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - image: nginx
        name: nginx